tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "bash-completion"
brew "composer"
brew "git"
brew "gnupg"
brew "mas"
brew "nvm"
brew "readline"
brew "php"
brew "postgresql", restart_service: true
brew "pyenv"
brew "pyenv-virtualenv"
brew "rethinkdb", restart_service: true
brew "tree"
brew "wget"
brew "xz"
cask "avast-security"
cask "betterzip"
cask "cd-to-terminal"
cask "datagrip"
cask "devdocs"
cask "discord"
cask "docker"
cask "google-chrome"
cask "java"
cask "keepingyouawake"
cask "keycastr"
cask "macs-fan-control"
cask "ngrok"
cask "phpstorm"
cask "postman"
cask "pycharm"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "skype"
cask "sublime-text"
cask "suspicious-package"
cask "vagrant"
cask "vagrant-manager"
cask "virtualbox"
cask "vlc"
cask "webstorm"
cask "whatsapp"
mas "Lightshot Screenshot", id: 526298438
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
