tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "bash-completion"
brew "composer"
brew "git"
brew "gnupg"
brew "mas"
brew "nvm"
brew "postgresql", restart_service: true
brew "pyenv"
brew "tree"
brew "wget"
cask "avast-security"
cask "cd-to-terminal"
cask "discord"
cask "google-chrome"
cask "java"
cask "keepingyouawake"
cask "macs-fan-control"
cask "ngrok"
cask "phpstorm"
cask "pycharm"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "sublime-text"
cask "suspicious-package"
cask "webstorm"
mas "Lightshot Screenshot", id: 526298438
mas "Slack", id: 803453959
