tap "homebrew/bundle"
tap "lotyp/homebrew-formulae"

# TODO: Check the installed packages see what they are, also delete unnecessary ones
# TODO: make sure to delete any bootstrapping code for deleted packages
# TODO: Compare with my old dotfiles bundle and see what we can add here
# core/dotfiles
brew "bats-core"
brew "coreutils"
brew "duti"
brew "lotyp/formulae/dockutil"
brew "nano"
brew "stow"
brew "thefuck"
brew "topgrade"
brew "mas"
brew "mackup"

# fs/network
brew "bat"
brew "croc"
#brew "httpie" # brings http and https command line tools in, simple cURL alternatives, designed for APIs
brew "ssh-copy-id"
brew "tree"
brew "unar"
brew "wget"
brew "zoxide"

# search/grep/diff
brew "fd"
brew "fzf"
brew "git-delta"
brew "gnu-sed"
brew "grep"
brew "jq"
brew "psgrep"
brew "ripgrep"
brew "the_silver_searcher"

# languages/tools
brew "gh"
brew "n"
brew "python"
brew "ruby"
brew "rust"
brew "shellcheck"
brew "autoenv"
brew "libpq"

# media
brew "ffmpeg"
brew "imagemagick"
brew "uni"
brew "webp"

# misc
brew "grip"
