name: Check Markdown links

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 3 * * 2" # Run every Tuesday at 3:00 AM

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: HarryVasanth/markdown-link-checker@v1
        with:
          verbose: "true"
